### ISSUE TITLE
Unexpected token '<'

### ISSUE THREAD

**Issue by treboryx** [eidellev/inertiajs-adonisjs#68]
Anyone getting this error when adding the following in inertia config?

```
  ssr: {
    enabled: true,
    mode: 'react', // can also be 'vue2', 'vue3', 'svelte'
    pageRootDir: 'js/pages', // Where inertia should look for page components
  }
```

Without it, all good, but no SSR.

**Comment by eidellev** [comment]
Hey @treboryx !
This is probably because you don't have `jsx` enabled in your `tsconfig.json`
this way this currently works is that inertia relies on adonis's `tsconfig` when rendering things on the server.
This may change in the future, but i'll update the docs just in case.

Feel free to reopen if this doesn't fork for you.
